@startuml
' Cooling modes - SC_Eric
|SC_Eric|
!theme aws-orange

start
:Select Control Index 3 (Cooling control mode);

if (Mode? ) then (0x00 Internal)
    :Device autonomously controls pump & fans\nusing internal sensors;
    :Set W1.Control Index 5 (PWM source);

    if (PWM source?) then (0x00 Internal)
        :Internal temperature sensor used to\ncontrol pump and fan speeds;
    else (0x01 External)
        :PWM from host controls pump & fan speeds;
        note right
            Controls.CPU Temp
            Controls.GPU Temp
        end note
    endif

    if (Temperature sensor and\nfan curve available?) then (yes)
        :Working mode select;
        fork
            :Load FAN curve for each motor\nand calculate output PWM for each motor;
        fork again
            :PID control;
        end fork
        :Send out PWM value by UART TX;
        stop
    else (no)
        if (SC has available PWM input\n(motherboard sync)?) then (yes)
            :Pass through PWM percentage setting\nto the sub-device;
            :Send out PWM value by UART TX;
            stop
        else (no)
            :Fall back mode:\napply 50% PWM to the sub-device;
            :Send out PWM value by UART TX;
            stop
        endif
    endif

else (0x01 External)
    :Pump and fans are controlled by the app;
    :Set W1.Control Index 1 (Pump power %);
    :Set W1.Control Index 2 (Fans power %);
    :Send out PWM value by UART TX;
    stop
endif
@enduml