@startuml daisy-chain

' Entities
entity "Big Controller 1" as BC_1
entity "Big Controller 2" as BC_2
entity "Small Controller 1" as SC_1
entity "Small Controller 2" as SC_2
entity "Small Controller 3" as SC_3
entity "W1_1"
entity "F1_1"
entity "F1_2"
entity "F1_3"


' Daisy-chain links between controllers
BC_1 -- SC_1
BC_1 -- BC_2
SC_1 -- SC_2
BC_2 -- SC_3

' External links
W1_1 --> SC_1
F1_1 --> SC_2
F1_2 --> BC_2
F1_3 --> SC_3 

@enduml