@startuml

  [*] --> Detected

state Detected {
  Detected: Device has USB PID of the supported device
  Disconnected: SN is known
  Detected --> Connected : Plug USB
  Connected --> Disconnected : Unplug USB
}

state Connected {
  Connected --> ActiveSession : Session activated \nin QLink
  ActiveSession --> Normal
  ActiveSession : Device has valid active session via QLink
  Normal : Fully operating device
  ActiveSession --> Limited
  Limited: Limited operating device when daisy-chained
  Connected : Device is detected as a valid USB device via QLink
  Connected --> InactiveSession
  InactiveSession : Session not activated in QLink
  InactiveSession --> Reactivate
  Reactivate :Prompt to activate session
  InactiveSession --> KillOtherApp
  KillOtherApp : Prompt to turn off other applications
  Connected --> Bootloader
  Bootloader : Device is in Bootloader while the FW updated
  Bootloader --> FW_stuck
  Bootloader --> HardError
  FW_stuck : Prompt to restart FW update
  Connected --> DeviceError : Device reported \nen error
  DeviceError --> SoftError
  DeviceError : Device reported internal error
  SoftError : Prompt to reset to Default
  DeviceError --> HardError
  HardError : Prompt to contact support
}
@enduml